### ISSUE TITLE
Error on loading algorithms

### ISSUE THREAD

**Issue by nyalldawson** [jjenkner/ClusterPoints#1]
This was previously fixed in https://github.com/jjenkner/ClusterPoints/commit/376c83d97b8201a0e48987ca70151d21705b6981, but then https://github.com/jjenkner/ClusterPoints/commit/76e83eff6a6819a8a7c3fe420fbc5e612d5a9d15 reverted the changes and the original issue has resurfaced.

**Comment by jjenkner** [comment]
Which QGIS version are you using?

**Comment by nyalldawson** [comment]
It's an issue in any qgis version - if you open and the accept the options dialog you'll get an error. loadAlgorithms needs to return a new instance of the algorithms, not a recycled instance

**Comment by jjenkner** [comment]
Dear Nyall, I reverted ClusterPoints.py to the status of 376c83d. Due to the current circumstances, I'm not at home and only have access to a very old computer. Hence, I can't test the code. I pushed a new commit to github. Maybe, you can verify that it's working now? Then, I can upload the code to the QGIS repository. Thank you in advance!

**Comment by jjenkner** [comment]
The new version 3.7.1 in the QGIS plugin repository should be fine now.

**Comment by nyalldawson** [comment]
Looks good, thanks!
